name: Lint & Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v5.0.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run next build
        env:
          HACKMD_PROFILE: ${{ secrets.HACKMD_PROFILE }}
          ABOUT_ME_NOTE_ID: ${{ secrets.ABOUT_ME_NOTE_ID }}
          DOMAIN: ${{ secrets.DOMAIN }}
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
        run: pnpm build
